spring.application.name=chatbot
server.port=8087


#------Gemini Configuration ------
spring.ai.google.genai.api-key=${gemini_api_key}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash


spring.ai.mcp.client.streamable-http.connections.mcprh.url=http://localhost:8989/mcp
#spring.ai.mcp.client.streamable-http.connections.ebank.url=http://localhost:8077/mcp
telegram.api.key=${telegram_api_bot}