spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=1
        - id: r2
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
        - id: r3
          uri: lb://BILLING-SERVICE
          predicates:
            - Path=/api/bills/**
          filters:
            - StripPrefix=1